In [3]:
import numpy as np
np.array([1,3,5,7])
A = np.mat([[1,2],[3,3]])
A

matrix([[1, 2],
        [3, 3]])

In [4]:
A + A

matrix([[2, 4],
        [6, 6]])

In [5]:
A * A

matrix([[ 7,  8],
        [12, 15]])

In [6]:
np.linalg.det( A )

-3.0000000000000004

In [7]:
np.matrix.transpose(A)

matrix([[1, 3],
        [2, 3]])